name: MDFEniCSx CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "main"

jobs:
  flake8:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        paths: [" "]
    steps:
      - name: Install flake8
        uses: py-actions/flake8@v2
        with:
          max-line-length: "500"
          paths: ${{ matrix.paths }}
  test:
    runs-on: ubuntu-latest
    container: dolfinx/dolfinx:v0.7.2
    strategy:
      fail-fast: false
      procs: ["1", "2", "3"]
    steps:
       - name: Checkout code
         uses: actions/checkout@v4
       - name: Test dolfinx
         run: |
           python3 --version
           cd demo/0_fundamental_deformation/mesh_data/
           mpiexec -n 1 python3 mesh.py
           cd ..
           mpiexec -n ${{ matrix.procs }} python3 0_fundamentals.py


  # ### Flake8 tests
