name: MDFEniCSx CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "main"

jobs:
  flake8:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Install flake8
        uses: py-actions/flake8@v2
        env:
          ignore=E128,F401
        with:
          max-line-length: "500"
          path: [" "]
  test:
    runs-on: ubuntu-latest
    container: dolfinx/dolfinx:v0.7.2
    strategy:
      fail-fast: false
    steps:
       - name: Checkout code
         uses: actions/checkout@v4
       - name: Test dolfinx
         run: |
           python3 --version


  # ### Flake8 tests
