name: MDFEniCSx CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "main"

jobs:
  flake8:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        paths: [" "]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install flake8
        uses: py-actions/flake8@v2
        with:
          max-line-length: "79"
          paths: ${{ matrix.paths }}
  test:
    runs-on: ubuntu-latest
    container: dolfinx/dolfinx:v0.7.3
    strategy:
      fail-fast: false
      matrix:
        procs: ["1", "2"]
        tuts: ["0_fundamental_deformation", "1_harmonic_mesh_deformation", "2_linear_elastic_mesh_deformation", "3_airfoil_displacement", "4_deformation_on_internal_boundary",         "5_deformation_on_part_of_the_boundary", "6_free_form_deformation"]
    steps:
       - name: Checkout code
         uses: actions/checkout@v4
       - name: Install mdfenicsx
         run: |
           python3 -m pip install .
       - name: Test dolfinx
         run: |
           python3 --version
           cd demo/${{ matrix.tuts }}/mesh_data/
           mpiexec -n 1 python3 mesh.py
           cd ..
           mpiexec -n ${{ matrix.procs }} python3 *.py
           cd ..
